apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-toleration
spec:
  replicas: 2
  selector:
    matchLabels:
      type: toleration-test
  template:
    metadata:
      labels:
        type: toleration-test
    spec:
      containers:
      - name: ct-toleration
        image: nginx
        ports:
        - containerPort: 80
      tolerations:
      - key: "ready"
        operator: "Equal"
        value: "yes"
        effect: "NoSchedule"
