apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-a
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: pv-a
  nfs:
    path: /mnt/pool-1/peserta3
    server: 10.23.1.150
---
