apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nodename
spec:
  replicas: 2
  selector:
    matchLabels:
      type: nodename-test
  template:
    metadata:
      labels:
        type: nodename-test
    spec:
      nodeName: kube-node1
      containers:
      - name: ct-nodename
        image: nginx
        ports:
        - containerPort: 80
