apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: nginx
    env: dev
  annotations:
    desc: "balaaasdadasdasdasdadadasdadadasdasdassraasd"
  name: pod-limit
spec:
  containers:
  - image: nginx
    name: ct-nginx
    ports:
     - containerPort: 80
    resources:
      requests:
        memory: "1024Mi"
        cpu: "10m"
      limits:
        memory: "1024Mi"
        cpu: "80m"
