apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: nginx
    env: dev
  annotations:
    desc: "balaaasdadasdasdasdadadasdadadasdasdassraasd"
  name: pod-port
spec:
  containers:
  - image: nginx
    name: ct-nginx
    ports:
     - containerPort: 80
    #resources: {}
    #dnsPolicy: ClusterFirst
    #restartPolicy: Always
    #status: {}
