apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-vol
spec:
  volumes:
  - name: secret-volume
    secret:
      secretName: my-secret
  containers:
    - name: ct-secret-vol
      image: nginx
      volumeMounts:
          - name: secret-volume
            mountPath: /etc/secret-volume
